### ISSUE TITLE
Interactive demo

### ISSUE THREAD

**Issue by jcubic** [chunqiuyiyu/ervy#10]
I've found a link in your project in one of my old text note and I've used your library as demo for jQuery Terminal (will link it in example page). 

https://codepen.io/jcubic/pen/gObPBdP?editors=0010

![chart](https://user-images.githubusercontent.com/280241/70480550-4de3e980-1ae0-11ea-94f1-65508831bed6.png)

this can be way to document the project, examples are always great way to showcase the API. You can add command one for each plot/chart. And code for the terminal don't add much boilerplate.

(the welcome message can of course showcase your project and version)

If you don't have time and want this, and if you confirm that you will include the demo with link to my project (terminal.jcubic.pl and my name in credit section or other place) I can take a time to create demo of all your plots.

**Comment by chunqiuyiyu** [comment]
@jcubic Thanks for your help, I'm very glad to add link of your project and name to Ervy's README.md file, Once you have finished it, I will update README.md file.

**Comment by jcubic** [comment]
Another working plot is pie chart.

**Comment by jcubic** [comment]
Demo is working, all plots except scatter plot that have bugs in ANSI codes #14 if you fix that bug the demo should work, there is also help command that show how plot commands should work. And there is demo command that show sample plots.

**Comment by jcubic** [comment]
There is still issue with scatter plot but if you use 1 ch wide dots it works correctly:
https://codepen.io/jcubic/pen/gObPBdP?editors=0010

![screencapture-cdpn-io-jcubic-debug-gObPBdP-VGrWNxRKbepM-2020-01-03-17_20_31](https://user-images.githubusercontent.com/280241/71734947-6203d800-2e4d-11ea-99e8-5d52b65d0408.png)

**Comment by chunqiuyiyu** [comment]
I have updated the README.md file.

**Comment by jcubic** [comment]
Nice, I thought that you will use on website https://www.chunqiuyiyu.com/ervy/ I'm not sure what page is give more visitors, you can embed the terminal directly on the page. With better greetings (maybe your ASCII art). Like try yourself directly on the page.

Is this the website https://github.com/chunqiuyiyu/ervy/tree/master/site? I can create PR with demo directly on that page.

**Comment by chunqiuyiyu** [comment]
Yes, It is. Your PR is welcome!

**Comment by jcubic** [comment]
It seems this is solved long ago.
