### ISSUE TITLE
Piechart errors

### ISSUE THREAD

**Issue by jcubic** [chunqiuyiyu/ervy#11]
Check my demo: https://codepen.io/jcubic/pen/gObPBdP?editors=0010

commands:
```
pie A:10:green B:20:$ C:30:red
```
it renders half of the circle

and this one is komplety broken:
```
pie A:10:green B:20:$ C:30:red d:10:blue
```

The code just pass the data to `ervy.pie`.

![ervy](https://user-images.githubusercontent.com/280241/70854600-2ca74280-1ebe-11ea-8f34-a65e8f91e580.png)

**Comment by chunqiuyiyu** [comment]
@jcubic I think you should add whitespace(' ') to single character when you want to render pie chart. Check the demo code:  https://github.com/chunqiuyiyu/ervy/blob/master/demo/index.js#L23

**Comment by jcubic** [comment]
The first is working but the second is still broken:

![chart2](https://user-images.githubusercontent.com/280241/70910462-0d202f00-2010-11ea-8090-9c07a0847b22.png)

**Comment by chunqiuyiyu** [comment]
Because the ASCII characters are "rough", sometimes the size of each area cannot be calculated correctly. You must manually add a property: gapChar, for example:

```js
const pieData = [
  { key: 'A', value: 10, style: bg('green', 2) },
  { key: 'B', value: 20, style: '$$' },
  { key: 'C', value: 30, style: bg('red', 2) },
  { key: 'D', value: 10, style: bg('blue', 2) }
]

console.log(pie(pieData, { gapChar: bg('blue', 2)  }))
```
Result:

![image](https://user-images.githubusercontent.com/7722205/71007551-244f4180-2122-11ea-89b7-9d06c2246689.png)

For automatic processing programs, pie charts sometimes do not display correctly if there are too many blocks inside( your example above).

**Comment by jcubic** [comment]
How do you know that gap need to be blue without looking the output?

**Comment by chunqiuyiyu** [comment]
No way to know that before the output. My suggestion is not to deal with this situation.

**Comment by jcubic** [comment]
So you say, that it randomly create wrong results and to fix the issue, just don't create data that will create this random results?

This is definitely a bug in the library, that should handle edge cased and produce valid results, or if not it's of no use. You never know if pie chart will be correct.

**Comment by chunqiuyiyu** [comment]
You are right, I have fixed it in version 1.0.5. Now, gapChar would be the style of last value in renderer data.

**Comment by jcubic** [comment]
But which entry need this, I can add option, it's no difference if I need to guess which item need this gap. This is just not consistent API. it give random values.

**Comment by chunqiuyiyu** [comment]
You don't need to guess it, now Ervy will auto generate the gapChar.

**Comment by jcubic** [comment]
I've updated to 1.0.5 and it still, broken, no auto generate:
![ervy2](https://user-images.githubusercontent.com/280241/71325247-50840d00-24ea-11ea-9603-761510b135ed.png)

**Comment by chunqiuyiyu** [comment]
How do you update the Ervy? My test for this error is passed.

**Comment by jcubic** [comment]
I think I did, I've updated the npm package generated the file using browserfiy but it's hard to tell because you don't provide UMD so you can't use https://unpkg.com/ and you don't have version string in your code. So the file can be any version.

**Comment by jcubic** [comment]
How to create pie correct chart with this data, can you provide the code? Do you need to pun anywhere `gapChar`? To be sure I've just installed gain the library and generated new file, it's the same. Are you sure that you've commited the changes it look like the diff commit is almost no different the previous code, it only get gapChar from options, there are no any auto generation.

**Comment by chunqiuyiyu** [comment]
Check this newest commit:https://github.com/chunqiuyiyu/ervy/commit/b7d1bfd197d8ae419051111accf676ebf0131ce1, I remove gapChar from options, and generate it from styles.

**Comment by jcubic** [comment]
style is added by user if you don't provide it as option it will not work, and you need to put it only in one data and you can't know before you generate which data need this gap, you said it's autogenerated how come if you need to specify as option only for one item.

**Comment by jcubic** [comment]
Sorry, I've build the file in wrong way, the pie chart is working also my demo show correct piechart.

**Comment by jcubic** [comment]
You should update demo file since it's only documentation right now, it still have gapChar as option.
