### ISSUE TITLE
Scatter chart doesn't print values of 1

### ISSUE THREAD

**Issue by nicolaibach** [chunqiuyiyu/ervy#18]
Hi, I have a strange problem with the scatter chart. Somehow the Y Axis starts at 2 and not 1.

+ macOS version 10.15.7
+ Terminal.app version 2.10

The code:

```js
const options = {
  legendGap: 4,
};

const data = [
  { key: "A", value: [1, 1] },
  { key: "A", value: [2, 2] },
  { key: "A", value: [3, 3] },
  { key: "A", value: [4, 4] },
];

console.log(ervy.scatter(data, options));
```

And this is the result:

<img width="378" alt="Screenshot 2021-12-11 at 16 20 57" src="https://user-images.githubusercontent.com/19892350/145681977-3310d9f5-91f8-4778-b601-a190d885ccfa.png">

Am I missing something?
Thank you very much!

**Comment by chunqiuyiyu** [comment]
Hi, you shoud add enough space to show value near by axis, for example:
```
const options = {
    legendGap: 4,
    vGap: 3,
    zero: '+'
};
```
output:
![image](https://user-images.githubusercontent.com/7722205/145810819-f2595d9e-b45f-4797-8bc4-10c86b87599b.png)

**Comment by nicolaibach** [comment]
Yes, works like a charm. Thank you very much!
